### ISSUE TITLE
Suggestion: Provide `property_resolver` from hackernews demo as helper

### ISSUE THREAD

**Issue by ginger51011** [obi1kenobi/trustfall#151]
First of all, great job with making this demo A LOT more readable!

Looking at the two macros in `demo-hackernews/src/adapter.rs`, `property_resolver` seems generic enough to just be a helper?

I can do this later today if it is something we want.

Edit: Also, I think `resolve_property` (or at least its arms) could be replaced with a macro... I'll experiment a bit

**Comment by ginger51011** [comment]
See [this branch](https://github.com/ginger51011/trustfall/tree/feat/add-resolve-property-to-core)

**Comment by ginger51011** [comment]
Come to think of it, perhaps there should be another macro that simply takes all three arguments in

```rust
resolve_property_with(...)
```

directly.

Although we might be careful with naming here, as it's already becoming a bit muddy 😅

**Comment by obi1kenobi** [comment]
I absolutely *love* the example you wrote. You have an amazing talent for understanding and explaining things clearly, and I'm so glad you're here!

> perhaps there should be another macro that simply takes all three arguments

I'm thinking this too, and I'm thinking we should add it first because it's much more common to use these together than to need _just_ the `property_resolver` macro. We can always add the intermediate macro later if needed, and it's one fewer name we have to come up with 😅 

How about something usable like:
```
("User", "id") => property_from_field!(contexts, id)
```
or if a conversion is needed first:
```
("User", "name") => property_from_field!(contexts, as_user, name)
```

Sometimes the value will be an accessor method, not a field, so we could have a parallel macro `property_from_accessor` that looks the same but just adds the `()` after the method name.

Another naming option is to add a module and make it idiomatic to reference through the module: `property::field!(...)` and `property::accessor!(...)`.

**Comment by ginger51011** [comment]
Good input. Honestly the whole match statement is so standardized, as well as the types themselves, that we might even want to make the abstractions even higher level, and provide an example with the expanded code in the docs to show "This is what we want, make your types like this and this is what you get"

Looking at the macros for `juniper` might be an inspiration actually, see [docs.rs](https://docs.rs/juniper/latest/juniper/attr.graphql_object.html). Is this way of doing it something we could use as a model maybe?

**Comment by obi1kenobi** [comment]
> Good input. Honestly the whole match statement is so standardized, as well as the types themselves, that we might even want to make the abstractions even higher level, and provide an example with the expanded code in the docs to show "This is what we want, make your types like this and this is what you get"

Yes, absolutely! In general, I see `trustfall_core` as providing the "OS syscalls" level of abstraction: super powerful but too low-level for most use cases. The reason most of the higher-level abstractions don't exist yet is that I didn't want to build them poorly. I have a strong "either do it properly or don't do it at all" streak when it comes to infrastructure 😅

> Looking at the macros for `juniper` might be an inspiration actually, see [docs.rs](https://docs.rs/juniper/latest/juniper/attr.graphql_object.html). Is this way of doing it something we could use as a model maybe?

That looks very nice, great find! I think something like that should definitely exist — probably in its own crate, though, just to minimize semver/breakage concerns.

Is this something you'd care to prototype? No pressure at all, obviously.

**Comment by ginger51011** [comment]
I'd absolutely love to try, but we're moving at the edges of my experience to be honest.

**Comment by obi1kenobi** [comment]
Same here! Happy to learn together if you're up for it, but no worries if not.

**Comment by obi1kenobi** [comment]
I added some more helper macros in #152, and in the process found another couple of possible candidate macros. What do you think?

At this rate, I'm starting to think that maybe those helpers would be better off in a separate crate at some point...?

**Comment by ginger51011** [comment]
Exciting, I'll give you a code review if you want!

I am unsure with separate crates. If you want to go with a `trustfall` crate, I think it should go there. For me at least, if I want to start a project, I don't want to add 3 different dependencies to do one thing

**Comment by obi1kenobi** [comment]
I'd love a review! I already merged the PR so I can get started on the next one more easily, but I'll fix any issues you find.

Also, if you'd like to port your awesome docs example from your commit to the macros, please do! I think it'd be great, and I didn't want to just copy-paste it in my own commit since it's your work and should be credited to you in the git history :)

Makes sense on not having too many dependencies. I'll keep it in core for now, and we can move it as needed in the future.

**Comment by ginger51011** [comment]
It's getting a bit late for me here (central European), so I'll be more thorough tomorrow.

Looking at it really does make it seem easier to create adaptors, amazing work really! If anything this really does reveal that for some cases, such as feed, it is very possible do have standard solutions.

If I'm gonna comment anything, I would probably advice against renaming functions in the demos (like `neighbors`). I get your point and would do the same in prod, but it's just another things you have to look up.

I'll go ahead with some docs for this tomorrow, or at least porting mine...

**Comment by obi1kenobi** [comment]
Much appreciated!

I was really on the fence about renaming vs not. With the renaming, most of the match arms ended up being one-liners, whereas before almost all of them were on multiple lines with curly braces which was its own flavor of "difficult to read." This felt like the lesser of two evils.

**Comment by obi1kenobi** [comment]
Safe to close based on #152 and #156?

If you get a chance to look, let me know if you think the `impl_downcast!()` and `iterable!()` macros from [here](https://github.com/obi1kenobi/trustfall/pull/152/files#diff-0bd2c8d48384244de50127aaf2999ff15f67fbb6d36b9eeb99d97f47165c58acR32-R60) might be worth bringing into `helpers`.

I'm not thrilled with their names right now. Here's what they do:
- `impl_downcast!()` generates an `fn as_foo(&self) -> Option<&Foo>` method. For adapters that adopt the "`Vertex` is an enum across underlying vertex types" paradigm (likely ~most of them), this may remove a bunch of boilerplate.
- `iterable!()` is sort of analogous to `field_property!()` but for neighboring edges: "apply conversion, access a field, call `.iter()` on it, and `.map()` a function that turns each item into a vertex. It's more niche than the property macros, because a smaller (but still noticeable) fraction of edges will be amenable to this. It should probably also have both field and accessor variants.

**Comment by ginger51011** [comment]
Yes we can close!

We should probably try to follow the [Rust naming guidelines](https://rust-lang.github.io/api-guidelines/naming.html), but yeah I think those would make good additions! But the names should change, because `iterable` is very ambiguous...

I also kind of feel like `impl_downcast` could have some arguments removed, it is basically taking the same parameter three times (with variations). Maybe we want to make it simple to rename methods, but I'm not sure...

**Comment by obi1kenobi** [comment]
> I also kind of feel like `impl_downcast` could have some arguments removed, it is basically taking the same parameter three times (with variations). Maybe we want to make it simple to rename methods, but I'm not sure...

The first and third argument overlap and could be deduplicated, but I think that would involve proc macros (+dependencies, longer compile times for everyone, etc.) since we need to construct identifiers on the fly (`CapCamelCase -> snake_case` and prepend `as_` prefix). The second argument is the underlying type, which is sometimes [a more complex type than in that example](https://github.com/obi1kenobi/trustfall-rustdoc-adapter/blob/rustdoc-v24/src/adapter.rs#L127).
