### ISSUE TITLE
Pytrustfall version not updated with recent features release

### ISSUE THREAD

**Issue by luz5** [obi1kenobi/trustfall#248]
Hi Predrag! This is Ziyi. Looks like [pytrustfall version](https://pypi.org/project/trustfall/#description) is not updated despite the release of new features in the trustfall-core. 

The latest release of the pytrustfall was labeled with the same version number (0.1.6) as the previous release. Is this intentional? what is the best practice to use the newest version?

**Comment by obi1kenobi** [comment]
Hey Ziyi! Great to hear from you!

I'll release a new version as soon as I fix the bug in #205, since it'll involve a breaking API change on the Rust side. On the Python side, you shouldn't notice anything and the API should stay the same as in 0.1.6. I'm hoping the new version should be ready by Monday or Tuesday, but you shouldn't have to wait for it because it shouldn't block you — just use 0.1.6 for now and re-lock later.

I also need to dig into the code for marking releases, because there's something clearly a bit misconfigured with it. If you happen to have the time and inclination to look, please feel free to open pull requests!

**Comment by luz5** [comment]
Thanks! Maybe this is a stupid question but do we have ways to access `query_info` in V0.1.6 as repo-query uses hints to do optimization? I see in the latest release `query_info` was added, but v0.1.6 does not seems to expose this info.

**Comment by obi1kenobi** [comment]
Not a stupid question at all, just incomplete docs :)

`query_info` is being reworked on the Rust side and will be split into
`ResolveInfo` and `ResolveEdgeInfo` in the next release. Unfortunately I
haven't had a chance to do the "plumbing" for Python yet, so neither the
old nor the new types will be available just yet.

I know it's important for repo-query and will unlock lots of awesome new
lints that have been waiting for a long time to be implemented. Right now
this is a one-person free open source project, and there are many
priorities competing for my time. It'll definitely get added eventually
(happy to review PRs!) but if it's waiting on me to build it, I can't offer
a specific timeline.

Might Kensho be open to becoming a sponsor of the Python bindings and
support the development of new functionality? It would cost a tiny fraction
compared to SWE time, and when someone is financially sponsoring the
project, I can justify bumping up the priority of important features since
the support directly makes the project healthier.

I'd be thrilled to work together again, and I'd love to make this a
win-win! Let me know what you think!

**Comment by luz5** [comment]
Sure thing! I will see what I can do and put up a PR (no promises, need to learn how to use pyo3 first lol). Thanks again for the help!

**Comment by obi1kenobi** [comment]
Awesome!

It's actually probably best to start by designing the Python-equivalent interface for `ResolveInfo`, `ResolveEdgeInfo`, `EdgeInfo`, etc. Those will need to be defined in Python as well in order for their type hints and autocompletions to be visible to users in their editor.

So if you'd like to start there, you shouldn't need any pyo3 for a while.

**Comment by obi1kenobi** [comment]
The new Trustfall v0.4 APIs are now published and stable, so it should be safe to port them to Python. @luz5 is that still something you're interested in doing?

**Comment by luz5** [comment]
Sure thing! I can work on it this or next week. will put up PR as I go, so you can review it and make sure I am on the right track. Thanks!

**Comment by obi1kenobi** [comment]
Sounds great! Excited to get your help on this!

**Comment by luz5** [comment]
Hi Predrag, I wanted to reach out and apologize for the delay. I had to deal with unexpected water damage last week : ( 
Will leverage wellness day this week to work on this, just letting you know I did not forget this.
